#!/bin/bash

export PROJECT_NAME="duplicate-file-finder"
export SRC="src"
export TESTS="tests"
export TEST_WATCH_PATTERN="{$SRC,$TESTS}/**/*.js"
export INDEXGEN_PATHS="$SRC"
export LINT_PATHS="$SRC $TESTS"

function task() {
    echo "$1 started"
    "tasks/$1" "${@:2}"
    EXIT_CODE=$?
    echo
    echo "exit code $EXIT_CODE"
}

time task $@
echo
exit $EXIT_CODE
