#!/bin/bash

export PROJECT_NAME="duplicate-file-finder"
export SRC="src"
export MODULES="$SRC/modules"
export TESTS="tests"
export TEST_WATCH_PATTERN="{$SRC,$TESTS}/**/*.js"
export INDEXGEN_PATHS="$MODULES"
export LINT_PATHS="$SRC $TESTS"
