#!/bin/bash

export PROJECT_NAME="duplicate-file-finder"
export SRC="src"
export MODULES="$SRC/modules"
export TESTS="tests"
export TEST_HELPERS="test-helpers"
export TEST_WATCH_PATTERN="{$SRC,$TESTS,$TEST_HELPERS}/**/*.js"
export INDEXGEN_PATHS="$MODULES $TEST_HELPERS"
export LINT_PATHS="$SRC $TESTS"
