#!/bin/bash
  
. ./task-vars

node \
--experimental-specifier-resolution=node \
--input-type=module \
- "$README_TEMPLATE" < ./tasks/lib/readme-file-generator.js > "$README"

npx doctoc --maxlevel 2 "$README"
